services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    image: app:latest
    environment:
      FLASK_ENV: development
      DATABASE_URI: postgresql://${POSTGRES_USER:-myuser}:${POSTGRES_PASSWORD:-mypassword}@${POSTGRES_HOST:-127.0.0.1:5432}/${POSTGRES_DB:-mydatabase}
    ports:
      - "8081:8080"

volumes:
  postgres_data:
